-- 迁移 0033：计价规则增加「计费方式」
--
-- 意图（Why）：
--   在此之前，"免费"只能靠"不配价格"来表达，于是两种完全不同的意图在数据上
--   长得一模一样：
--     1) 我有意让这个模型免费（活动模型、公益分组）；
--     2) 我还没来得及给它定价（漏配）。
--   后果很实际：后台看不出哪些模型是"故意免费"、哪些是"漏了"，
--   模型广场也没法标出"免费"，用户只能靠试算去猜。
--
--   本列把计费方式变成一个显式选择：免费 / 按量（token）/ 按次（per_call）。
--
-- 取值语义：
--   ''        = 自动判定（默认，也是全部历史数据的取值）：
--               只有按次价、没有 token 价 → 按次；其余按量。
--               这样升级后既有规则的计费行为【逐字不变】。
--   'free'    = 显式免费：无论价格字段填了什么，一律不计费。
--               显式的意义在于"我确认过它是免费的"，与漏配区分开。
--   'token'   = 按 token 计费（输入/输出/缓存三个价）。
--   'per_call'= 按次计费（图像 / 视频 / 异步任务类）。
--
-- 兼容性：
--   只加列、不改既有列；默认空串让既有数据的判定走"自动"分支，
--   与迁移前的行为完全一致（不会因为升级而突然开始或停止收费）。
--
-- 流转（Flow）：
--   model_prices.billing_mode → ModelPrice.EffectiveBillingMode
--     → Billing.Quote / QuoteOnce / Charge / EstimateReserve
--     → 模型广场按 billing_mode 显示「免费」标识
--
-- 扩展（Extend）：
--   新增计费方式（如阶梯计费）时：在本目录追加 NNNN_*.sql，并同步
--   model/model_price.go 的常量与 EffectiveBillingMode、
--   Billing 的四个计费入口，以及价格页的选项列表。

ALTER TABLE model_prices ADD COLUMN billing_mode TEXT NOT NULL DEFAULT '';
